import type { ProviderDatasetSeed } from './shared.ts'
import { usGeography, worldGeography } from './shared.ts'

export const anthropicDatasets: ProviderDatasetSeed[] = [
  {
    provider: 'anthropic',
    geoType: 'country',
    metricId: 'knowledge_work',
    metricLabel: 'Knowledge work intensity',
    description: 'Representative index-style signal for professional knowledge-work concentration by country.',
    valueType: 'index',
    comparabilityGroup: 'anthropic_knowledge_work',
    colorRamp: { low: '#0f766e', high: '#fb7185' },
    sourceUrl: 'https://www.anthropic.com/research/the-anthropic-economic-index-geography-and-energy',
    methodologyUrl: 'https://www.anthropic.com/economic-index',
    geography: worldGeography,
    periods: [
      {
        id: '2025-08',
        label: 'Aug 2025',
        publicationDate: '2025-08-18',
        values: { USA: 78, CAN: 71, GBR: 73, FRA: 60, DEU: 63, IND: 58, JPN: 56, BRA: 42, AUS: 69, SGP: 81 },
      },
      {
        id: '2025-11',
        label: 'Nov 2025',
        publicationDate: '2025-11-16',
        values: { USA: 82, CAN: 74, GBR: 76, FRA: 63, DEU: 67, IND: 62, JPN: 59, BRA: 45, AUS: 73, SGP: 85 },
      },
      {
        id: '2026-02',
        label: 'Feb 2026',
        publicationDate: '2026-02-18',
        values: { USA: 85, CAN: 77, GBR: 79, FRA: 66, DEU: 69, IND: 65, JPN: 62, BRA: 48, AUS: 76, SGP: 88 },
      },
    ],
  },
  {
    provider: 'anthropic',
    geoType: 'country',
    metricId: 'energy_alignment',
    metricLabel: 'Infrastructure alignment',
    description: 'Representative score-style signal for geography and energy alignment in Anthropic-style reporting.',
    valueType: 'score',
    comparabilityGroup: 'anthropic_energy_alignment',
    colorRamp: { low: '#0ea5e9', high: '#f43f5e' },
    sourceUrl: 'https://www.anthropic.com/research/the-anthropic-economic-index-geography-and-energy',
    methodologyUrl: 'https://www.anthropic.com/economic-index',
    geography: worldGeography,
    periods: [
      {
        id: '2025-08',
        label: 'Aug 2025',
        publicationDate: '2025-08-18',
        values: { USA: 65, CAN: 63, GBR: 59, FRA: 48, DEU: 56, IND: 51, JPN: 61, BRA: 39, AUS: 68, SGP: 72 },
      },
      {
        id: '2025-11',
        label: 'Nov 2025',
        publicationDate: '2025-11-16',
        values: { USA: 69, CAN: 66, GBR: 62, FRA: 51, DEU: 59, IND: 54, JPN: 64, BRA: 42, AUS: 72, SGP: 76 },
      },
      {
        id: '2026-02',
        label: 'Feb 2026',
        publicationDate: '2026-02-18',
        values: { USA: 72, CAN: 69, GBR: 65, FRA: 54, DEU: 61, IND: 57, JPN: 67, BRA: 45, AUS: 75, SGP: 79 },
      },
    ],
  },
  {
    provider: 'anthropic',
    geoType: 'us_state',
    metricId: 'knowledge_work',
    metricLabel: 'Knowledge work intensity',
    description: 'Representative state-level knowledge-work concentration within Anthropic-style reporting.',
    valueType: 'index',
    comparabilityGroup: 'anthropic_knowledge_work',
    colorRamp: { low: '#0f766e', high: '#fb7185' },
    sourceUrl: 'https://www.anthropic.com/research/the-anthropic-economic-index-geography-and-energy',
    methodologyUrl: 'https://www.anthropic.com/economic-index',
    geography: usGeography,
    periods: [
      {
        id: '2025-08',
        label: 'Aug 2025',
        publicationDate: '2025-08-18',
        values: { CA: 82, NY: 76, TX: 62, WA: 79, MA: 78, VA: 68, IL: 63, CO: 67 },
      },
      {
        id: '2025-11',
        label: 'Nov 2025',
        publicationDate: '2025-11-16',
        values: { CA: 85, NY: 79, TX: 65, WA: 82, MA: 81, VA: 71, IL: 66, CO: 70 },
      },
      {
        id: '2026-02',
        label: 'Feb 2026',
        publicationDate: '2026-02-18',
        values: { CA: 88, NY: 82, TX: 68, WA: 84, MA: 83, VA: 74, IL: 69, CO: 72 },
      },
    ],
  },
  {
    provider: 'anthropic',
    geoType: 'us_state',
    metricId: 'energy_alignment',
    metricLabel: 'Infrastructure alignment',
    description: 'Representative state-level infrastructure and energy alignment signal.',
    valueType: 'score',
    comparabilityGroup: 'anthropic_energy_alignment',
    colorRamp: { low: '#0ea5e9', high: '#f43f5e' },
    sourceUrl: 'https://www.anthropic.com/research/the-anthropic-economic-index-geography-and-energy',
    methodologyUrl: 'https://www.anthropic.com/economic-index',
    geography: usGeography,
    periods: [
      {
        id: '2025-08',
        label: 'Aug 2025',
        publicationDate: '2025-08-18',
        values: { CA: 63, NY: 58, TX: 66, WA: 61, MA: 57, VA: 59, IL: 54, CO: 64 },
      },
      {
        id: '2025-11',
        label: 'Nov 2025',
        publicationDate: '2025-11-16',
        values: { CA: 67, NY: 61, TX: 70, WA: 64, MA: 60, VA: 63, IL: 57, CO: 68 },
      },
      {
        id: '2026-02',
        label: 'Feb 2026',
        publicationDate: '2026-02-18',
        values: { CA: 70, NY: 64, TX: 73, WA: 66, MA: 62, VA: 65, IL: 60, CO: 71 },
      },
    ],
  },
]
