import type { ProviderDatasetSeed } from './shared.ts'
import { usGeography, worldGeography } from './shared.ts'

export const openaiDatasets: ProviderDatasetSeed[] = [
  {
    provider: 'openai',
    geoType: 'country',
    metricId: 'consumer_reach',
    metricLabel: 'Consumer reach',
    description: 'Representative share-style signal for broad public adoption by country.',
    valueType: 'share',
    unit: '%',
    comparabilityGroup: 'openai_consumer_reach',
    colorRamp: { low: '#155e75', high: '#f59e0b' },
    sourceUrl: 'https://openai.com/global-affairs/openai-signals/',
    methodologyUrl: 'https://openai.com/signals/data-download/',
    geography: worldGeography,
    periods: [
      {
        id: '2025-10',
        label: 'Oct 2025',
        publicationDate: '2025-10-25',
        values: { USA: 72, CAN: 66, GBR: 68, FRA: 54, DEU: 56, IND: 63, JPN: 49, BRA: 44, AUS: 64, SGP: 70 },
      },
      {
        id: '2026-01',
        label: 'Jan 2026',
        publicationDate: '2026-01-28',
        values: { USA: 78, CAN: 71, GBR: 74, FRA: 60, DEU: 62, IND: 69, JPN: 55, BRA: 49, AUS: 69, SGP: 75 },
      },
      {
        id: '2026-02',
        label: 'Feb 2026',
        publicationDate: '2026-02-28',
        values: { USA: 81, CAN: 74, GBR: 77, FRA: 63, DEU: 65, IND: 73, JPN: 58, BRA: 52, AUS: 72, SGP: 79 },
      },
    ],
  },
  {
    provider: 'openai',
    geoType: 'country',
    metricId: 'developer_depth',
    metricLabel: 'Developer depth',
    description: 'Representative score-style signal for advanced developer usage depth by country.',
    valueType: 'score',
    comparabilityGroup: 'openai_developer_depth',
    colorRamp: { low: '#1d4ed8', high: '#f97316' },
    sourceUrl: 'https://openai.com/global-affairs/openai-signals/',
    methodologyUrl: 'https://openai.com/signals/data-download/',
    geography: worldGeography,
    periods: [
      {
        id: '2025-10',
        label: 'Oct 2025',
        publicationDate: '2025-10-25',
        values: { USA: 61, CAN: 57, GBR: 58, FRA: 46, DEU: 50, IND: 59, JPN: 48, BRA: 39, AUS: 55, SGP: 64 },
      },
      {
        id: '2026-01',
        label: 'Jan 2026',
        publicationDate: '2026-01-28',
        values: { USA: 66, CAN: 61, GBR: 63, FRA: 50, DEU: 55, IND: 64, JPN: 53, BRA: 43, AUS: 60, SGP: 69 },
      },
      {
        id: '2026-02',
        label: 'Feb 2026',
        publicationDate: '2026-02-28',
        values: { USA: 69, CAN: 63, GBR: 65, FRA: 53, DEU: 58, IND: 67, JPN: 56, BRA: 46, AUS: 62, SGP: 72 },
      },
    ],
  },
  {
    provider: 'openai',
    geoType: 'us_state',
    metricId: 'consumer_reach',
    metricLabel: 'Consumer reach',
    description: 'Representative state-level consumer adoption signal within the US drill-down.',
    valueType: 'share',
    unit: '%',
    comparabilityGroup: 'openai_consumer_reach',
    colorRamp: { low: '#155e75', high: '#f59e0b' },
    sourceUrl: 'https://openai.com/global-affairs/openai-signals/',
    methodologyUrl: 'https://openai.com/signals/data-download/',
    geography: usGeography,
    periods: [
      {
        id: '2025-10',
        label: 'Oct 2025',
        publicationDate: '2025-10-25',
        values: { CA: 79, NY: 74, TX: 67, WA: 73, MA: 70, VA: 64, IL: 61, CO: 59 },
      },
      {
        id: '2026-01',
        label: 'Jan 2026',
        publicationDate: '2026-01-28',
        values: { CA: 84, NY: 78, TX: 71, WA: 77, MA: 74, VA: 68, IL: 66, CO: 63 },
      },
      {
        id: '2026-02',
        label: 'Feb 2026',
        publicationDate: '2026-02-28',
        values: { CA: 87, NY: 81, TX: 74, WA: 79, MA: 76, VA: 71, IL: 68, CO: 66 },
      },
    ],
  },
  {
    provider: 'openai',
    geoType: 'us_state',
    metricId: 'developer_depth',
    metricLabel: 'Developer depth',
    description: 'Representative state-level advanced usage depth for development-heavy workflows.',
    valueType: 'score',
    comparabilityGroup: 'openai_developer_depth',
    colorRamp: { low: '#1d4ed8', high: '#f97316' },
    sourceUrl: 'https://openai.com/global-affairs/openai-signals/',
    methodologyUrl: 'https://openai.com/signals/data-download/',
    geography: usGeography,
    periods: [
      {
        id: '2025-10',
        label: 'Oct 2025',
        publicationDate: '2025-10-25',
        values: { CA: 71, NY: 62, TX: 58, WA: 69, MA: 64, VA: 57, IL: 52, CO: 55 },
      },
      {
        id: '2026-01',
        label: 'Jan 2026',
        publicationDate: '2026-01-28',
        values: { CA: 75, NY: 66, TX: 61, WA: 73, MA: 68, VA: 61, IL: 56, CO: 59 },
      },
      {
        id: '2026-02',
        label: 'Feb 2026',
        publicationDate: '2026-02-28',
        values: { CA: 78, NY: 69, TX: 64, WA: 76, MA: 71, VA: 63, IL: 58, CO: 62 },
      },
    ],
  },
]
